// This file is auto-generated by scripts/ascii/index.ts
// Do not edit manually - your changes will be overwritten

import defaultAlphabet from "./default.json";
import ascii60Alphabet from "./ascii-60.json";
import programmingAlphabet from "./programming.json";
import pixelAlphabet from "./pixel.json";
import pixelshortAlphabet from "./pixel-short.json";

const alphabets = {
  "default": defaultAlphabet,
  "ascii-60": ascii60Alphabet,
  "programming": programmingAlphabet,
  "pixel": pixelAlphabet,
  "pixel-short": pixelshortAlphabet,
} as const;

export type AlphabetName = keyof typeof alphabets;

export function getAvailableAlphabets(): AlphabetName[] {
  return Object.keys(alphabets) as AlphabetName[];
}

export function getAlphabetCharacterVectors(name: AlphabetName) {
  return alphabets[name].characters;
}

export function getAlphabetMetadata(name: AlphabetName) {
  return alphabets[name].metadata;
}
