// This file is auto-generated by scripts/ascii/index.ts
// Do not edit manually - your changes will be overwritten

import defaultAlphabet from "./default.json";
import ascii60Alphabet from "./ascii-60.json";
import programmingAlphabet from "./programming.json";
import pixelAlphabet from "./pixel.json";
import pixelshortAlphabet from "./pixel-short.json";
import threesamplesAlphabet from "./three-samples.json";
import twosamplesAlphabet from "./two-samples.json";

const alphabets = {
  "default": defaultAlphabet,
  "ascii-60": ascii60Alphabet,
  "programming": programmingAlphabet,
  "pixel": pixelAlphabet,
  "pixel-short": pixelshortAlphabet,
  "three-samples": threesamplesAlphabet,
  "two-samples": twosamplesAlphabet,
} as const;

export type AlphabetName = keyof typeof alphabets;

export function getAvailableAlphabets(): AlphabetName[] {
  return Object.keys(alphabets) as AlphabetName[];
}

export function getAlphabetCharacterVectors(name: AlphabetName) {
  return alphabets[name].characters;
}

export function getAlphabetMetadata(name: AlphabetName) {
  return alphabets[name].metadata;
}

export function getCharacterVector(char: string, alphabet: AlphabetName): number[] {
  const characters = alphabets[alphabet].characters;
  const charData = characters.find(c => c.char === char);
  if (charData) {
    return charData.vector;
  }
  // Fallback to space character
  const spaceData = characters.find(c => c.char === ' ');
  return spaceData ? spaceData.vector : [];
}
