// This file is auto-generated by scripts/ascii/index.ts
// Do not edit manually - your changes will be overwritten

import defaultAlphabet from "./default.json";
import simpledirectionalcrunchAlphabet from "./simple-directional-crunch.json";
import pixelshortAlphabet from "./pixel-short.json";
import twosamplesAlphabet from "./two-samples.json";
import sixsamplesAlphabet from "./six-samples.json";

export const alphabets = {
  "default": defaultAlphabet,
  "simple-directional-crunch": simpledirectionalcrunchAlphabet,
  "pixel-short": pixelshortAlphabet,
  "two-samples": twosamplesAlphabet,
  "six-samples": sixsamplesAlphabet,
} as const;

export type AlphabetName = keyof typeof alphabets;
