// Generated by Claude

import { CharacterSamplingData } from "./generateAsciiChars";
import { AsciiRenderConfig } from "../renderConfig";
import { AlphabetName, getCharacterVector } from "../alphabets/AlphabetManager";

export function generateCharacterGridSamplingData(
  characterString: string,
  config: AsciiRenderConfig,
  alphabet: AlphabetName,
) {
  const lines = characterString.split("\n");
  const contentRows = lines.length;
  const contentCols = Math.max(...lines.map((line) => line.length));

  // Calculate centering offsets
  const rowOffset = Math.floor((config.rows - contentRows) / 2);
  const colOffset = Math.floor((config.cols - contentCols) / 2);

  // Build centered grid with padding
  const samplingData: CharacterSamplingData[][] = [];

  for (let row = 0; row < config.rows; row++) {
    const samplingDataRow: CharacterSamplingData[] = [];

    for (let col = 0; col < config.cols; col++) {
      const sourceRow = row - rowOffset;
      const sourceCol = col - colOffset;

      let char = " ";
      if (
        sourceRow >= 0 &&
        sourceRow < contentRows &&
        sourceCol >= 0 &&
        sourceCol < lines[sourceRow].length
      ) {
        char = lines[sourceRow][sourceCol];
      }

      const vector = getCharacterVector(char, alphabet);
      samplingDataRow.push({
        samplingVector: vector,
        rawSamplingVector: vector,
        externalSamplingVector: [],
        samplingVectorSubsamples: [],
        character: char,
      });
    }

    samplingData.push(samplingDataRow);
  }

  return { samplingData };
}
