const FONT_SIZE = 18;
const LINE_HEIGHT_FACTOR = 1.5;
const LINE_HEIGHT = FONT_SIZE * LINE_HEIGHT_FACTOR;
const V_PADDING = 24;
const SCRIPTED_EDITOR_MIN_WIDTH = 640;
const SCRIPT_NAVIGATION_WIDTH = 348;
const SCRIPT_NAVIGATION_BREAKPOINT = 1180;
const SCRIPT_NAVIGATION_DRAWER_HEIGHT = 214;

export const scriptedEditorConstants = {
  FONT_SIZE,
  LINE_HEIGHT_FACTOR,
  LINE_HEIGHT,
  V_PADDING,
  SCRIPTED_EDITOR_MIN_WIDTH,
  SCRIPT_NAVIGATION_WIDTH,
  SCRIPT_NAVIGATION_BREAKPOINT,
  SCRIPT_NAVIGATION_DRAWER_HEIGHT,
};
